### ISSUE TITLE
TCP congestion algorithm [kernel]

### ISSUE THREAD

**Issue by Fedsd1** [BYZYB/android_device_xiaomi_libra#10]
有可能支持bbr吗

**Comment by BYZYB** [comment]
目前只有 Linux-4.9+ 支持以 BBR 作为 TCP 拥塞算法 （所以这个 issue 其实应该提交到 [WJXXBSH/android_kernel_xiaomi_libra](https://github.com/WJXXBSH/android_kernel_xiaomi_libra/issues)，不过没有关系），~~而这个模块应该和内核的其他部分没有太多关联，~~ 因此我可以尝试从 [android-linux-stable/msm-4.9](https://github.com/android-linux-stable/msm-4.9) 反向移植。如果可行的话我会再回复的。

**Comment by BYZYB** [comment]
> 目前只有 Linux-4.9+ 支持以 BBR 作为 TCP 拥塞算法 （所以这个 issue 其实应该提交到 [WJXXBSH/android_kernel_xiaomi_libra](https://github.com/WJXXBSH/android_kernel_xiaomi_libra/issues)，不过没有关系），~而这个模块应该和内核的其他部分没有太多关联，~ 因此我可以尝试从 [android-linux-stable/msm-4.9](https://github.com/android-linux-stable/msm-4.9) 反向移植。如果可行的话我会再回复的。

昨天我低估了内核中 TCP 部分从 3.10 到 4.9 的变化程度，从目前的情况来看，暂时无法在不影响内核中其他部分的情况下移植 BBR（况且还需要 [fq pacing](https://gmd20.github.io/blog/Linux%E5%86%85%E6%A0%B8%E7%9A%84tcp-BBR%E5%92%8Ctcp-pacing/) 才能正常运行，而目前的内核并不支持）。之前看到有人尝试把 BBR 移植到 3.10，不过以“问题太多”告终；虽然不能说完全“不可能”，不过短时间内我显然是无法提供 BBR 支持的，抱歉。

如果你有足够的时间，也可以接着我目前的进度继续（只解决了一部分问题，比如把依赖 tcp_cc_info 的部分转换为旧内核支持的形式）：
[BACKPORT: lib/win_minmax: windowed min or max estimator](https://github.com/WJXXBSH/android_kernel_xiaomi_libra/commit/2857b507f8bc0dc2a6392c2af3083c2e3316f424)
[BACKPORT: tcp_bbr: add BBR congestion control](https://github.com/WJXXBSH/android_kernel_xiaomi_libra/commit/ae15a9c105b6517dfdb5eecc26eef57b9ac39697)

**Comment by Fedsd1** [comment]
> > 目前只有 Linux-4.9+ 支持以 BBR 作为 TCP 拥塞算法 （所以这个 issue 其实应该提交到 [WJXXBSH/android_kernel_xiaomi_libra](https://github.com/WJXXBSH/android_kernel_xiaomi_libra/issues)，不过没有关系），~而这个模块应该和内核的其他部分没有太多关联，~ 因此我可以尝试从 [android-linux-stable/msm-4.9](https://github.com/android-linux-stable/msm-4.9) 反向移植。如果可行的话我会再回复的。
> 
> 昨天我低估了内核中 TCP 部分从 3.10 到 4.9 的变化程度，从目前的情况来看，暂时无法在不影响内核中其他部分的情况下移植 BBR（况且还需要 [fq pacing](https://gmd20.github.io/blog/Linux%E5%86%85%E6%A0%B8%E7%9A%84tcp-BBR%E5%92%8Ctcp-pacing/) 才能正常运行，而目前的内核并不支持）。之前看到有人尝试把 BBR 移植到 3.10，不过以“问题太多”告终；虽然不能说完全“不可能”，不过短时间内我显然是无法提供 BBR 支持的，抱歉。
> 
> 如果你有足够的时间，也可以接着我目前的进度继续（只解决了一部分问题，比如把依赖 tcp_cc_info 的部分转换为旧内核支持的形式）：
> [BACKPORT: lib/win_minmax: windowed min or max estimator](https://github.com/WJXXBSH/android_kernel_xiaomi_libra/commit/2857b507f8bc0dc2a6392c2af3083c2e3316f424)
> [BACKPORT: tcp_bbr: add BBR congestion control](https://github.com/WJXXBSH/android_kernel_xiaomi_libra/commit/ae15a9c105b6517dfdb5eecc26eef57b9ac39697)

抱歉，我没有相关的知识储备，只是问一下有没有实现的可能，如果不行那就算了吧
