### ISSUE TITLE
Unstable under prolonged hotspot use [lineage-17.1]

### ISSUE THREAD

**Issue by tempte** [BYZYB/android_device_xiaomi_libra#11]
Usually 1-3 hours of activated hotspot with moderate data traffic (5-15 mbit) leads to one or several issues:
- UI freeze, temporary or constant lack of response, inability to turn on screen with power button.
- Apps failure to respond (app stopped responding notification).
- Unexpected system restart, inability to manual restart (infinite "restarting" screen) with only option to hard restart (long press of power button).
- Data transmission interruption, inability to turn on hotspot after it was turned off (infinite "turning on").

In case none of above issues noted - more time of hotspot use will definitely lead to one of them. The battery is 100% charged so no influence of overheating from charge/quick charge.

**Comment by BYZYB** [comment]
I never use hotspot for such a long time, that's why this problem isn't found before. Could you disable "Tethering hardware acceleration" in "Settings - Developer options" and "Wi-Fi scanning" in "Settings - Location"? The problems you mentioned seem like a crash of qcacld-2.0 wlan driver, so it's recommended to install [this new kernel](https://cowtransfer.com/s/c2aa228db2564c) (link-exp: 24 hours), then try hotspoting again.

**Comment by tempte** [comment]
Thank you for updated kernel. With above options disabled and new kernel it seems to be stable now, will see how it will behave in the long run (Btw tethering hardware acceleration is disabled by default). Other combination of options with old/new kernel led to same issues. 

The only issue discovered so far - after longer (several hours) hotspot use (even after turning it off) deep sleep state is not in use anymore, after reboot everything works again.

**Comment by tempte** [comment]
Unfortunately faced same issues under longer hotspot use with new kernel, disabled Tethering hardware acceleration and disabled WiFi scanning

**Comment by BYZYB** [comment]
> Unfortunately faced same issues under longer hotspot use with new kernel, disabled Tethering hardware acceleration and disabled WiFi scanning

Could you try the [latest pre-release](https://github.com/WJXXBSH/android_device_xiaomi_libra/releases/tag/v2020.08.12) to see if there is any change? The wlan driver has been updated in that version, I felt more stable when using wlan than the past.

**Comment by tempte** [comment]
So far it behaves stable, none of above stability issues noticed except deepsleep issue (smth. prevents the phone going into deepsleep mode after hotspot use). Will report in case of other problems appear. Btw should "Tethering hardware acceleration" be enabled or disabled - any performance benefits for this device/SOC?

**Comment by BYZYB** [comment]
> So far it behaves stable, none of above stability issues noticed except deepsleep issue (smth. prevents the phone going into deepsleep mode after hotspot use). Will report in case of other problems appear. Btw should "Tethering hardware acceleration" be enabled or disabled - any performance benefits for this device/SOC?

I think "Tethering hardware acceleration" should work on modern devices like Pixel 3/4, and may not work on Mi-4c. If this feature doesn't cause new bugs, just keep it enabled.

**Comment by tempte** [comment]
Can confirm that under latest ROM there are no bugs listed previously (except deepsleep) during several days of use, even with "Wi-Fi scanning" and "Tethering hardware acceleration" enabled. The only issue is no deepsleep mode after prolonged hotspot use - is there any possible solution to try?

**Comment by BYZYB** [comment]
> Can confirm that under latest ROM there are no bugs listed previously (except deepsleep) during several days of use, even with "Wi-Fi scanning" and "Tethering hardware acceleration" enabled. The only issue is no deepsleep mode after prolonged hotspot use - is there any possible solution to try?

The issue of deep sleep has a long history on Mi-4c (may back to Android 7.x, I even thought deep sleep is not supported at that time). It's less than a year when I realized there's something wrong in qcacld-2.0 wlan driver and tried some ways to fix it.
For now, after adjusting wlan configs and upgrading the driver, deep sleep should work in most situations. I use wlan hotspot less than 3 times a year, so some problems may not be able to find in time. I'm not sure if it could be fixed (in a short time), but I'll deal with it after resolving the issue of call volume.
It's recommended to disable "Wi-Fi scanning" unless you really need it.
