### ISSUE TITLE
[Request] How to install Google Camera

### ISSUE THREAD

**Issue by gordio** [BYZYB/android_device_xiaomi_libra#15]
Hey, is it possible to use Google Camera (Camera API 2, HAL3 etc…)?

**Comment by WJXXBSH** [comment]
For camera API2/HAL3, I have made a [patch](https://androidfilehost.com/?fid=8889791610682882449) for it months ago. You can install it in TWRP (remember to backup your system first) and check if API2/HAL3 is enabled. However, this feature has a few bugs which may affect your daily use. Only some versions of Google Camera works, but I don't remember the exact version number (at least, the first version uses API2/HAL3 works on my device, try to find it at APKMirror).

**Comment by BYZYB** [comment]
> Hey, is it possible to use Google Camera (Camera API 2, HAL3 etc…)?

For camera API2/HAL3, I have made a [patch](https://androidfilehost.com/?fid=8889791610682882449) for it months ago. You can install it in TWRP (remember to backup your system first) and check if API2/HAL3 is enabled. However, this feature has a few bugs which may affect your daily use. Only some versions of Google Camera works, but I don't remember the exact version number (at least, the first version uses API2/HAL3 works on my device, try to find it at APKMirror).

**Comment by gordio** [comment]
Awesome. Latest Google Camera from Google Play partly worked.
- Video ok, Photos Front Cam ok (at low light 3/4 with green layer), Face Cam ok.
**Problems**: Autofocus, Extra don't work (Panorama, Photo Sphere, Lens Blur).

[mm-camera.log (Start/Stop Google Camera)](https://github.com/WJXXBSH/android_device_xiaomi_libra/files/5842215/mm-camera.log)

P.S. Where to find that lib `"/system/lib/hw/sensors.hal.tof.so" not found`?

**Comment by BYZYB** [comment]
>   **Problems**: Autofocus, Extra don't work (Panorama, Photo Sphere, Lens Blur).

These issues also exist on MIUI ROMs (Android 7.0) if API2/HAL3 is force enabled by system property. Unfortunately, Xiaomi didn't provide any further camera enhancements to Mi-4c after that (MIUI Android 5.1 → 7.0).

> P.S. Where to find that lib `"/system/lib/hw/sensors.hal.tof.so" not found`?

There is no TOF sensor on Mi-4c, so this lib is not needed. The open-source camera driver used in my patch is also a generic one, which is not fully adapted for Mi-4c (in experimental state).

**Comment by gordio** [comment]
Sadness…

**Comment by tempte** [comment]
Try "hypercam final 6.1" mod, version for Android 10. Worked for me (with few stability issues). Don't forget to reinstall HAL3 patch each time you upgrade ROM
