### ISSUE TITLE
Something goes wrong [lineage-20210116]

### ISSUE THREAD

**Issue by claraqwq** [BYZYB/android_device_xiaomi_libra#16]
**Describe the bug**
[New boot image](https://github.com/WJXXBSH/android_device_xiaomi_libra/releases/tag/v2021.01.16) swipe in causes Mi-4c to restart indefinitely

**To Reproduce**
After the boot image is swiped in, the phone will automatically restart soon after boot, and the bug will reappear. The old version of **boot-20200907-0110e54.img** is swiped in to solve the problem.

**Environment :**
 - Android: 10 
 - Kernel: 3.10.108-g0110e5499ab
 - Release: Lineage-17.1-20210116
 - GAPPs/Magisk: None

**Comment by BYZYB** [comment]
> **Describe the bug**
> [New boot image](https://github.com/WJXXBSH/android_device_xiaomi_libra/releases/tag/v2021.01.16) swipe in causes Mi-4c to restart indefinitely
> 
> **To Reproduce**
> After the boot image is swiped in, the phone will automatically restart soon after boot, and the bug will reappear. The old version of **boot-20200907-0110e54.img** is swiped in to solve the problem.
> 
> **Environment :**
> 
> * Android: 10
> * Kernel: 3.10.108-g0110e5499ab
> * Release: Lineage-17.1-20210116
> * GAPPs/Magisk: None

For the issue about random reboot: Did you enable CPU overclock in `Settings > Battery > Battery saver and performance > High performance mode`? Some Mi-4c may not be capable of overclocking, which will result in random reboot after version 20201216. You can disable (exactly, enable then disable if you didn't use this option before) overclock in Settings (or set system property "persist.sys.cpu_overclock" to "false") and check if this issue is resolved.

**Comment by claraqwq** [comment]
There is no overclocking. If you swipe in the new boot image, it will restart all the time, but if you swipe in the old boot image, it will be OK

**Comment by BYZYB** [comment]
> There is no overclocking. If you swipe in the new boot image, it will restart all the time, but if you swipe in the old boot image, it will be OK

My own Mi-4c (3/32) works properly with the latest ROM and kernel. Are you sure `persist.sys.cpu_overclock` is set to `false` on your device? Please note that if this property is unset (or that setting is never used), overclock will be enabled by default (it's the drawback of using system property + init.rc as a feature switch).

I suspect that overclock is one of the most possible reasons, but there are still some changes may cause reboot (from 2020/9 to 2021/1):
- CPU overclock
- Build toolchains changed from gcc-10 to clang-11
- F2FS backport from upstream
- KTM (msm_thermal) changes
- ...

If this issue keeps happening after clean install build 20210116 (remember to backup your data first), try to catch kernel or Android logs and post them here. Also, did your device reboot before the boot animation (white "android" logo)?

（注：可以用中文）

**Comment by claraqwq** [comment]
好吧，我这试了两种方法

1. 先刷boot再刷包
2. 刷包再刷boot（就是我发现无限重启后的做法）

都不行，后来找回之前刷过的boot（boot-20200907-0110e54.img）镜像就好了

**Comment by BYZYB** [comment]
> 好吧，我这试了两种方法
> 
> 1. 先刷boot再刷包
> 2. 刷包再刷boot（就是我发现无限重启后的做法）
> 
> 都不行，后来找回之前刷过的boot（boot-20200907-0110e54.img）镜像就好了

你的方法 1 和直接刷包没有区别，因为之前刷入的 boot 会被后者直接覆盖；如果方法 2 是把 `boot-20210116-43cef8e.img` 在安装 `lineage-17.1-20210116-UNOFFICIAL-libra.zip` 之后刷入的话，理论上也没有区别，因为前者是从后者中直接解压出来的（为了留作存档，除非前者文件名中的日期和后者不同，那样就相当于 nightly 版本的内核镜像）。

内核从去年 9 月到现在的更改比较多，不能直接确定是哪一项引发的问题（所以最好能提供内核日志或 logcat，假设 ADB 仍然可用）。如果你的 Mi-4c 在安装最新的内核之后（或者刷包之后不再刷入 boot-xxx.img）无限重启，且是在开机动画（白色的 "android" 图案）之前就重启了，大概可以排除超频引发问题的可能（根据之前的反馈，因为超频引发的重启问题通常会在开机后一段时间发生，甚至还有足够时间进入设置把“高性能模式”关掉）。如果是在开机动画之后、进入锁屏之前的那一段时间重启，且开机动画或锁屏界面在重启前的数秒内失去响应的话，就不能直接确定问题了（有多个可能的原因）。

为了缩小问题范围，你可以尝试刷入去年 12 月的内核镜像；如果还有问题，就刷入 11 月的试试（[链接](https://cowtransfer.com/s/9c9ee438bca24b)）。顺便问一下，你的 Mi-4c 是 2/16 还是 3/32 的版本？然后还有一个问题（虽然发生的概率不大），你手机的温度传感器工作正常吗（尤其是 CPU 温度，可以用 Devcheck 之类的应用查看，若不正常的话或许会长时间卡在一个温度值）？

**Comment by claraqwq** [comment]
> > 好吧，我这试了两种方法
> > 
> > 1. 先刷boot再刷包
> > 2. 刷包再刷boot（就是我发现无限重启后的做法）
> > 
> > 都不行，后来找回之前刷过的boot（boot-20200907-0110e54.img）镜像就好了
> 
> 你的方法 1 和直接刷包没有区别，因为之前刷入的 boot 会被后者直接覆盖；如果方法 2 是把 `boot-20210116-43cef8e.img` 在安装 `lineage-17.1-20210116-UNOFFICIAL-libra.zip` 之后刷入的话，理论上也没有区别，因为前者是从后者中直接解压出来的（为了留作存档，除非前者文件名中的日期和后者不同，那样就相当于 nightly 版本的内核镜像）。
> 
> 内核从去年 9 月到现在的更改比较多，不能直接确定是哪一项引发的问题（所以最好能提供内核日志或 logcat，假设 ADB 仍然可用）。如果你的 Mi-4c 在安装最新的内核之后（或者刷包之后不再刷入 boot-xxx.img）无限重启，且是在开机动画（白色的 "android" 图案）之前就重启了，大概可以排除超频引发问题的可能（根据之前的反馈，因为超频引发的重启问题通常会在开机后一段时间发生，甚至还有足够时间进入设置把“高性能模式”关掉）。如果是在开机动画之后、进入锁屏之前的那一段时间重启，且开机动画或锁屏界面在重启前的数秒内失去响应的话，就不能直接确定问题了（有多个可能的原因）。
> 
> 为了缩小问题范围，你可以尝试刷入去年 12 月的内核镜像；如果还有问题，就刷入 11 月的试试（[链接](https://cowtransfer.com/s/9c9ee438bca24b)）。顺便问一下，你的 Mi-4c 是 2/16 还是 3/32 的版本？然后还有一个问题（虽然发生的概率不大），你手机的温度传感器工作正常吗（尤其是 CPU 温度，可以用 Devcheck 之类的应用查看，若不正常的话或许会长时间卡在一个温度值）？

2+16
我关闭高性能模式刷入新的boot正常开机没有自动重启的现象了

**Comment by claraqwq** [comment]
温度的话有点高，只有两个大核心在跑，其他的显示离线

**Comment by BYZYB** [comment]
> 2+16
> 我关闭高性能模式刷入新的boot正常开机没有自动重启的现象了

看来确实是超频的问题，有一部分 Mi-4c 由于硬件体质等原因，可能会在超频后引发随机重启。设置中的“高性能模式”开关实际上对应系统属性 `persist.sys.cpu_overclock` 的值（true/false，可以通过 `getprop` 命令查看），但受实现方式所限没有对值为空的情况进行判断。不幸的是，无论是从此前版本升级还是清除数据后安装 ROM，这项属性默认均为空值（或不存在），只有在设置中切换“高性能模式”的状态或手动赋值之后才能生效；在值为空的情况下，系统启动时将不会设置 CPU 频率，而是使用默认值（即内核中设置的最高频率），所以超频实际上是默认启用的。

> 温度的话有点高，只有两个大核心在跑，其他的显示离线

如果核心温度持续超出 120℃，就会触发温控限制导致重启（如果传感器发生故障且返回的温度高于这个值，就会导致核心始终下线或是直接重启，这个情况虽然发生概率较低，但之前确实有过类似案例）；如果超出 70℃ 则会导致部分核心下线（目前是 CPU1/2/3/5，CPU0 和 CPU4 将始终在线）；当温度下降到 60℃ 时这些核心就会恢复上线。由于一些问题，目前未采用分阶段限制 CPU 核心频率减少发热的常规方案，而是通过限制在线核心的数量控制温度。
