### ISSUE TITLE
Unable to use gamepad [lineage-17.1]

### ISSUE THREAD

**Issue by WannaCyp0r** [BYZYB/android_device_xiaomi_libra#17]
Bt works fine when connect to a pc but disconnect almost immediately after connected to a gamepad.
Xbox one controller will constantly attempt to reconnect until timeout, DualShock 4 will just turn off. Both works fine when connected to a console or pc.

Environment:
 - Android 10
 - Kernel 3.10.108-g83f5f03bdb06
 - Release lineage-17.1-20210307-UNOFFICIAL-libra
 - Magisk 22.0
 - SELinux enforce

Log:
[logcat.log](https://github.com/WJXXBSH/android_device_xiaomi_libra/files/6221933/logcat.log)

**Comment by BYZYB** [comment]
> Bt works fine when connect to a pc but disconnect almost immediately after connected to a gamepad.
> Xbox one controller will constantly attempt to reconnect until timeout, DualShock 4 will just turn off. Both works fine when connected to a console or pc.
> 
> Environment:
> 
> * Android 10
> * Kernel 3.10.108-g83f5f03bdb06
> * Release lineage-17.1-20210307-UNOFFICIAL-libra
> * Magisk 22.0
> * SELinux enforce
> 
> Log:
> [logcat.log](https://github.com/WJXXBSH/android_device_xiaomi_libra/files/6221933/logcat.log)

I remember that the kernel configs about some kinds of HID devices (like gamepad) were disabled last year, in order to reduce the redundancy of the kernel. If you really need this feature, I could add them back in the next ROM update (you can also check for the latest kernel image [here](https://github.com/WJXXBSH/android_device_xiaomi_libra/releases/latest) for early access). 

Also, it's not recommended to use enforcing mode for SELinux, which may not be fully functional in some conditions.

**Comment by WannaCyp0r** [comment]
> > Bt works fine when connect to a pc but disconnect almost immediately after connected to a gamepad.
> > Xbox one controller will constantly attempt to reconnect until timeout, DualShock 4 will just turn off. Both works fine when connected to a console or pc.
> > Environment:
> > 
> > * Android 10
> > * Kernel 3.10.108-g83f5f03bdb06
> > * Release lineage-17.1-20210307-UNOFFICIAL-libra
> > * Magisk 22.0
> > * SELinux enforce
> > 
> > Log:
> > [logcat.log](https://github.com/WJXXBSH/android_device_xiaomi_libra/files/6221933/logcat.log)
> 
> I remember that the kernel configs about some kinds of HID devices (like gamepad) were disabled last year, in order to reduce the redundancy of the kernel. If you really need this feature, I could add them back in the next ROM update (you can also check for the latest kernel image [here](https://github.com/WJXXBSH/android_device_xiaomi_libra/releases/latest) for early access).
> 
> Also, it's not recommended to use enforcing mode for SELinux, which may not be fully functional in some conditions.

Then please enable them:)

**Comment by BYZYB** [comment]
> > > Bt works fine when connect to a pc but disconnect almost immediately after connected to a gamepad.
> > > Xbox one controller will constantly attempt to reconnect until timeout, DualShock 4 will just turn off. Both works fine when connected to a console or pc.
> > > Environment:
> > > 
> > > * Android 10
> > > * Kernel 3.10.108-g83f5f03bdb06
> > > * Release lineage-17.1-20210307-UNOFFICIAL-libra
> > > * Magisk 22.0
> > > * SELinux enforce
> > > 
> > > Log:
> > > [logcat.log](https://github.com/WJXXBSH/android_device_xiaomi_libra/files/6221933/logcat.log)
> > 
> > 
> > I remember that the kernel configs about some kinds of HID devices (like gamepad) were disabled last year, in order to reduce the redundancy of the kernel. If you really need this feature, I could add them back in the next ROM update (you can also check for the latest kernel image [here](https://github.com/WJXXBSH/android_device_xiaomi_libra/releases/latest) for early access).
> > Also, it's not recommended to use enforcing mode for SELinux, which may not be fully functional in some conditions.
> 
> Then please enable them:)

Just built a new [kernel image](https://github.com/WJXXBSH/android_device_xiaomi_libra/releases/download/v2021.03.07/boot-20210401-fd941e8.img) with some HID features enabled, could you have a try? I tested my Bluetooth mouse (a kind of HID device) on my own Mi-4c and it worked properly.

**Comment by WannaCyp0r** [comment]
> > > > Bt works fine when connect to a pc but disconnect almost immediately after connected to a gamepad.
> > > > Xbox one controller will constantly attempt to reconnect until timeout, DualShock 4 will just turn off. Both works fine when connected to a console or pc.
> > > > Environment:
> > > > 
> > > > * Android 10
> > > > * Kernel 3.10.108-g83f5f03bdb06
> > > > * Release lineage-17.1-20210307-UNOFFICIAL-libra
> > > > * Magisk 22.0
> > > > * SELinux enforce
> > > > 
> > > > Log:
> > > > [logcat.log](https://github.com/WJXXBSH/android_device_xiaomi_libra/files/6221933/logcat.log)
> > > 
> > > 
> > > I remember that the kernel configs about some kinds of HID devices (like gamepad) were disabled last year, in order to reduce the redundancy of the kernel. If you really need this feature, I could add them back in the next ROM update (you can also check for the latest kernel image [here](https://github.com/WJXXBSH/android_device_xiaomi_libra/releases/latest) for early access).
> > > Also, it's not recommended to use enforcing mode for SELinux, which may not be fully functional in some conditions.
> > 
> > 
> > Then please enable them:)
> 
> Just built a new [kernel image](https://github.com/WJXXBSH/android_device_xiaomi_libra/releases/download/v2021.03.07/boot-20210401-fd941e8.img) with some HID features enabled, could you have a try? I tested my Bluetooth mouse (a kind of HID device) on my own Mi-4c and it worked properly.

Tested, although no place to test rumble and gyro since I don't use them, but basic features(button, joystick and trigger) are working properly.
Closing.
