### ISSUE TITLE
Recent progress about this ROM

### ISSUE THREAD

**Issue by BYZYB** [BYZYB/android_device_xiaomi_libra#19]
Due to the disappointing fact that the battery on my own Mi-4c (which was bought more than 3 years ago, while the device itself was bought in 2015) has almost ran out of its life/capacity currently, and I cannot get a qualified new one for replacement (most products are out of stock, I even went to a service center of Xiaomi to ask for BM35 battery but failed)~, I may have to **end the active development** of [this project](https://forum.xda-developers.com/t/rom-8-1-9-10-unofficial-lineageos-for-mi-4c-mi-4s.4008625/) in a few months~.

My Mi-4c has become a meaningful item for myself that cannot be easy to say goodbye, so I will still find opportunities to change the battery and replace the rear cover. I have tried myself to improve the performance and user experience on Mi-4c, but it's obviously not possible to exceed the hardware limit of this device, which is a fact that I need to accept. I almost never use other mobile phone that doesn't belong to me in daily life, so the battery loss of my Mi-4c should be acceptable in such a condition. If I cannot get a new battery (a new rear cover is optional) before June 2021, it's the time for me to buy a new mobile phone as I will graduate from university and work for my company at that time.

**[Update on May, 2021]** I have bought a Xiaomi Mix 2 (like the picture below) as my new mobile phone, but my Mi-4c will still be kept at home. I won't sell it because it's meaningful to me, I also learned a lot from it (which have positive effects on my graduation project, and helped me to find my job last year). It's always a good thing if there is a new battery for Mi-4c with acceptable quality (sincerely thanks to @yipinghuang1991), so I plan to use it as backup or something interesting. I'm not sure if there is still plenty of time to put a lot of effort to Mi-Mix-2 (like what I did on Mi-4c) after going to work, but at least, I don't like to use MIUI or other stock ROMs (from device vendor) and I will build LineageOS (or just AOSP) including custom kernel for it (even though it's officially supported by LineageOS).

![My Mix-2](https://user-images.githubusercontent.com/34391595/117557990-77c18700-b0ab-11eb-9448-57b8238c7da7.jpg)

*Thanks to all developers and users who contributed to Mi-4c/Mi-4s (including other devices shipped with MSM8992/8994 SOC) or gave me help!*

**Comment by BYZYB** [comment]
In the last a few months, I will try to finish the following plans (maybe? but I need to finish my graduation project in first place):
- Android 11
  - Finished.
- ~New version of TWRP recovery based on Android 9.0 sources~
  - It could currently boot into TWRP splash screen and access ADB shell (so the kernel should be right), but failed to continue due to endless `segment  fault` of the executable of recovery. Maybe I should attach it to GDB debugger to find out what happened, if I have more free time.

**Comment by huwylphi** [comment]
Hi,
I'm also (still) a Mi-4c user, and replaced my battery with a [BM35 from Green Cell](https://greencell.global/en/xiaomi/2201-green-cell-battery-bm35-for-xiaomi-mi-4c.html) bought on amazon.
Almost 2 years later, the battery still work well. I'm currently not using this ROM but [crDroid](https://androidfilehost.com/?fid=6006931924117917896) with [Watermelon kernel-v2.7](https://forum.xda-developers.com/t/eas-kernel-libra-aqua-watermelon-kernel-v3-0-stable-linaro-5-4-1.3945771/).

**Comment by BYZYB** [comment]
> Hi,
> I'm also (still) a Mi-4c user, and replaced my battery with a [BM35 from Green Cell](https://greencell.global/en/xiaomi/2201-green-cell-battery-bm35-for-xiaomi-mi-4c.html) bought on amazon.
> Almost 2 years later, the battery still work well. I'm currently not using this ROM but [crDroid](https://androidfilehost.com/?fid=6006931924117917896) with [Watermelon kernel-v2.7](https://forum.xda-developers.com/t/eas-kernel-libra-aqua-watermelon-kernel-v3-0-stable-linaro-5-4-1.3945771/).

I visited the link you provided, but the battery there is also out of stock (just like other BM35 in Chinese online stores). The battery on my Mi-4c performs much worse than it was in late 2019 (the time I used it for about 2 years), seems like a normal result for Li-ion batteries that being used everyday.

Some parts of the kernel in my ROM is similar to Watermelon kernel (eg. EAS scheduler, F2FS backport, overclock or downclock...), and I prefer to use self-build ROMs rather than others (that's why I'm using lineage-17.1 currently).

**Comment by huwylphi** [comment]
Hi,
I'm sorry to hear that they are out of stock. I'm living in France and on amazon.fr they still have 3 in stock. Maybe if you can buy one from outside your country you could be lucky.

Regarding the rom and kernel, I'm following the progress of this rom and always wanted to try it, especially to be on lineage-17.1, but because of the following three points I never had the courage to make that step:
1. I'm using some 2FA app like Google Authenticator and if I install a new rom I don't know how to connect it back (maybe I would have to use backup codes...)
2. GPS reliability: in several of roms I've tested, the GPS reliability is not as good as in crDroid (might depend on location; I'm mostly in France/Switzerland)
3. time...

I think you might be one of the last one maintaining the Mi-4c, so many thanks for that! Maybe I will change my phone in some month but it's really hard to find one in that size... So if I find some courage I could finally give this rom a try ;)

**Comment by yipinghuang1991** [comment]
It seems to me that Taobao still has few allegedly genuine stock BM35.
Or maybe not? You live in China and what you said should be more accurate.

I purchased mine plus rear cover on online store back to December 2019 in Taiwan.
I am asking if there are still stock left. (It's very likely that the shop imports the items from mainland China when order is placed.)
And if I got one maybe let me send you for free?

**Comment by BYZYB** [comment]
> It seems to me that Taobao still has few allegedly genuine stock BM35.
> Or maybe not? You live in China and what you said should be more accurate.
> 
> I purchased mine plus rear cover on online store back to December 2019 in Taiwan.
> I am asking if there are still stock left. (It's very likely that the shop import the items from mainland China when order is placed.)
> And if I got one maybe let me send you for free?

Thanks for the info. I searched for BM35 battery on JD days ago, only some third party ones were available (similar situation like yours on Taobao). The sales volume of them are lower than normal, some even have no (valid) user comment. I'm not sure about the battery quality, as few of them are from the popular battery manufacturers I heard before.

I also went to a service center of Xiaomi to ask for information about BM35 battery, but the result is "suspended production a long time ago". They even looks kind of surprised (just as I expected) when I asked for changing battery for Mi-4c. According to the poor sales value of Mi-4c/4s (compared to Mi-4), what they said might be reasonable, and that's why few third party manufacturers still provide batteries for Mi-4c in 2021.

**Comment by BYZYB** [comment]
> In the last a few months, I will try to finish the following plans (maybe? but I need to finish my graduation project in first place):
> 
> * Android 11
>   
>   * It could currently goes into lockscreen and type password, but the system will crash in a few seconds. It even left no chance for ADB to transfer the logcat (at that important moment) to me, so I'm still not sure exactly what the real problem is.
> ...

During the Android 11 test in 12/5/2021, Mi-4c booted into desktop (as the picture below) at last, but stopped responding few seconds later. I could unlock my SIM card, unlock the lockscreen and see my desktop (yes, you can always upgrade from lineage-17.1 without a factory reset, just like 16.0 → 17.1 at past) before the crash.

![IMG_20210512_205432](https://user-images.githubusercontent.com/34391595/117984490-77a2df00-b36a-11eb-80d6-93bee84f9222.jpg)

According to such result, most changes between branch [lineage-17.1](https://github.com/BYZYB/android_device_xiaomi_libra/tree/lineage-17.1) and [lineage-18.1](https://github.com/BYZYB/android_device_xiaomi_libra) should not be wrong, maybe some essential parts are still missing, or I mistakenly did some wrong changes that I don't remember. ADB still crashed too early in the crash, made it difficult to get the logs at that moment (another way is `top -d 0.5`, which shows the process state at the last second, as the picture below).

![image](https://user-images.githubusercontent.com/34391595/117988170-bede9f00-b36d-11eb-86c0-8888755dd7ca.png)

Obviously, the back camera on my Mix-2 (bought as a second-hand product) must have some problem, makes it worse than the camera on Mi-4c. I need to check the back camera after take down the rear cover, another visit to Xiaomi service center is necessary if it's a hardware problem that I cannot fix. Fortunately, the device looks new enough (maybe the old owner used it only for weeks?), and I unlocked it successfully using the Mi account of my friend (without waiting for 7+ days).

**Comment by BYZYB** [comment]
Good news: **Lineage 18.1** will come soon.

Although the [device](https://github.com/BYZYB/android_device_xiaomi_libra/commits/lineage-18.1) and [vendor](https://github.com/BYZYB/android_vendor_xiaomi_libra/commits/lineage-18.1) changes of Android 11 have been finished mostly in late 2020, some other changes outside these repos still slowed down the progress of this project. Fortunately, I accidentally format my hard disk and ~~have to~~ have a clean start on my Android 11 project. Otherwise, I will not find the real cause of the problem in https://github.com/BYZYB/android_device_xiaomi_libra/issues/19#issuecomment-839785468 becuase there are too many local changes need to be checked.

![Screenshot_20210527-210739_Settings](https://user-images.githubusercontent.com/34391595/119834209-54fbf300-bf32-11eb-986e-cd7bacfa782e.png)

**Comment by BYZYB** [comment]
> Good news: **Lineage 18.1** will come soon.
> 
> Although the [device](https://github.com/BYZYB/android_device_xiaomi_libra/commits/lineage-18.1) and [vendor](https://github.com/BYZYB/android_vendor_xiaomi_libra/commits/lineage-18.1) changes of Android 11 have been finished mostly in late 2020, some other changes outside these repos still slowed down the progress of this project. Fortunately, I accidentally format my hard disk and ~have to~ have a clean start on my Android 11 project. Otherwise, I will not find the real cause of the problem in [#19 (comment)](https://github.com/BYZYB/android_device_xiaomi_libra/issues/19#issuecomment-839785468) becuase there are too many local changes (just like [repo_xx.diff](https://github.com/BYZYB/android_device_xiaomi_libra/blob/lineage-17.1/repo_17.diff)) need to be checked.

Just found the real problem: **Fsync cannot be enabled on Android 11** (including the `dynamic fsync` module in my kernel), which made me surprised. That's why ADB (or other user space programs) cannot give me useful logs when the system crashed, as it's a kernel panic. The kernel I tested yesterday had removed `dynamic fsync` and disabled `fsync` by default, because I planed to try some new things. However, those new changes were reverted back today because of some severe bugs. That's why the lineage-18.1 ROM today doesn't boot normally like the ones in the past. 

Such a coincidence, but the final result is still good. I'll remove the `dynamic fsync` module from kernel and use a more common and safe way instead. Also, the `nobarrier` mount option will be removed (to reduce the chance of data corruption), as `fsync` is disabled by default.

**Comment by Sherrysen** [comment]
您好，我是几年前给你打赏过的某人，不知道您是否还记得。

> 当时，我还是一个高中生，MIUI官方停止维护小米4C时，还能在XDA论坛看到您在维护，我当时就觉得小米4C真配得上当时有媒体说的“安卓小王子”的称号，而我当时也在把小米4C当成主力机使用，还把RAW升级成了4G，虽然存储只有16G，也用得津津有味。但当我过了一段时间再回到XDA看还有无更新时，看到您仍在维护，我瞬间对您有了respect，甚至是感动，所以有了打赏的念头，也想支持一下您的开发工作。我当时以为您已经拥有了工作，做小米4C的项目只是图一乐而已，但看到您最近的notice，才知道您刚大学毕业不久，而我现在已经是大二的学生了，才知道您的当初做这个项目的不简单，我对您肃然起敬。我很羡慕你的才华和维护小米4C的决心，我同样也希望自己能在大学期间能独立完成一个project，也是类似于这样的工程，但是我并非计算机科学或别的相关专业，我只是一个普通的工科生。

高中的时候，就希望自己能卷进计算机方面的专业，但是高考志愿有太多的不确定性，没能如愿选到自己喜欢的专业。

再次向题主表达敬意。

**Comment by BYZYB** [comment]
> 您好，我是几年前给你打赏过的某人，不知道您是否还记得。

当然记得，因为你是唯一成功（以非物质方式）捐赠我的人，另一个则是 https://github.com/BYZYB/android_device_xiaomi_libra/issues/19#issuecomment-820395860 中提到的新电池（例外：实际物质）。本项目属于非盈利性质，主要是为了学习和提升自身技能（虽然可能和未来的工作不直接相关，但自己喜欢就好，况且很多技能还是通用的），并尽力满足自己的日常使用需求，因此没有（也不会）提供公开的捐赠渠道，后续多人的主动捐赠也被我婉拒了。

其实目前还在维护 Mi-4c 这个老机型的并不只有我（国内：魔趣那边还有乖奕虎，这个存储库最初也 Fork 自对方，且对方还在维护更多机型，虽然听说要转手他人了），我能将这个项目继续下去的原因也很简单：唯一的手机是 Mi-4c 且有强烈的自我需求（这与对方不同）。因此，本项目最初只是为了满足自己的日常使用需求（可追溯到 Android 8.1 时代），后来感觉用着还不错就决定公开，这也是本系列 ROM 往往具有某些 ~~极端的~~ 特别之处的原因之一。即使上个月买到了成色不错的 Mix-2，也不会成为彻底结束这个项目的理由；一是六年来已经对我的 Mi-4c 有感情了（难以放下），二是新原装电池和后盖使其还能再续一段时间（至少出远门时电量不会太惨，之前的那块电池历史实在太悠久了）。

> 高中的时候，就希望自己能卷进计算机方面的专业，但是高考志愿有太多的不确定性，没能如愿选到自己喜欢的专业。

俗话说“行行出状元”，虽然现实可能并非如此，但这句话也是无可否认的。人生无常，高考更是如此 ~~（突然想起这两天就是高考）~~，能考入自己喜欢的学校、学习喜欢的专业固然是理想的，但不幸错过也不代表无法掌握自己的未来。至于是顺水推舟学好自己当前的专业，还是以其他方式另谋出路，就需要你权衡利弊并作出选择了。至于是否“卷”进去则取决于个人意愿，我选择计算机行业纯粹是因为喜欢（至少目前还是），因此工资（在广州）差不多少即可，也没有去互联网大厂的想法（与其去拼死拼活，莫不如找到合适的中小企业安静发展，即使牺牲薪资水平）。

作为参考：实际上，我高考也是被调剂到不理想的专业，但因为自幼喜欢和计算机等电子设备打交道，当初填报的志愿也都和计算机相关，因此并不甘心，于是有了申请转专业到计算机学院的计划。虽然大一上学期的第一次尝试因为 ~~当时太过内向连申请表都没敢交~~ 某些原因没能成功，但下学期终于顺利实现了目标，尽可能弥补了高考留下的遗憾。如果你有非常喜欢的专业（当然不局限于计算机类），也可以尝试申请转专业，但大二年级可能会来不及（那就学好当前的专业吧，我有个同学大二转专业结果降了一级，付出的代价可能还不如选择读研）。

> 再次向题主表达敬意。

也祝愿你能在大学期间实现自己的目标，毕业后找到一份理想的工作。
