### ISSUE TITLE
The bug I encountered in Lineage OS 18.1

### ISSUE THREAD

**Issue by laoleic4** [BYZYB/android_device_xiaomi_libra#22]
The first attempt to use English is not accurate
1. When opening QQ (version 8.0), it freezes and restarts
2. WiFi cannot be used after flashing into Gapps
3. After successfully activating QC2.0 fast charge, the temperature is too high and the machine restarts within a few minutes
4. After swiping in Gapps, open the settings-storage crashes and restarts
5. The Data partition cannot be viewed in TWRP 3.3.1 version, and it is suspected that the Data partition is encrypted(in 20210815)
6. Cannot enter the system after swiping into Week Gapps
7. After installing with a third-party Google installer, the settings are greatly changed, all the contents of the developer options are lost, the Bluetooth options are changed, and most applications freeze and restart.

从Github上看到你是国人，为了以防翻译出错打了下中文
1.打开QQ（8.0后版本）时死机重启（其他应用未知）
2.刷入Gapps后WiFi无法使用
3.成功激活QC2.0快充后没几分钟温度过高死机重启
4.刷入Gapps后打开设置-存储死机重启
5.Data分区在TWRP3.3.1版本中无法查看，疑似Data分区被加密（20210815的包遇到）
6.刷入Week Gapps后无法进入系统
7.使用第三方谷歌安装器安装后设置大变，开发者选项所有内容丢失，蓝牙选项发生变化，打开大部分应用死机重启

**Comment by BYZYB** [comment]
* GAPPs 相关问题
由于我自己不使用 GAPPs（账号也在数年前注销了），所以较少进行相关测试（至少 Android 11 还没有过），听其他用户说 BitGapps 是可行的（可能要留意 `/system` 的剩余空间，可以考虑把自带的 `webview` 安装到 `/data`，或者直接安装新版的 Google WebView 以留出额外的 100MB 空间）。如果在安装 GAPPs 后出现奇怪的问题，除了检查是否兼容之外，也不排除是问题 7 的可能（虽然未必是意外重启引起的）。

* 问题 1
刚测试了一下 8.8.20 版本，确实会引发重启，之前因为不用 QQ 就没发现过这个问题。第一印象感觉又像是内核问题（因为 ADB 没能来得及获取事发现场 log，而在内核崩溃时上层的 Android 是无法继续运行的），既然 QQ 是个臃肿的 APP，就推测是始终启用的大内存页（Linux 的 Transparent Hugepages 功能）引起的。临时禁用后发现确实是它的问题，大内存页理论上可以提升内存性能（减少页面总数，最坏情况则是多用一些内存），但也不排除 4c 的低版本内核存在一些问题，进而导致异常。目前暂时不打算在后续版本中禁用这个功能（毕竟才刚加入），你可以修改任意一个 `init.*.rc` 文件（例如在 `init.target.rc` 的 105 行），然后加入如下语句（可选 `madvise` 被动模式，或者 `never` 完全禁用）：
```
write /sys/kernel/mm/transparent_hugepage/enabled madvise
```
也可以使用命令行临时调整 Transparent Hugepages 的工作模式（需要启用 ADB Root）：
```
adb shell
    echo madvise > /sys/kernel/mm/transparent_hugepage/enabled
```

* 问题 3
高温重启确实是可能的（温度阈值是 120℃，这之前会尝试下线最多 4 个 CPU 核心以减少发热，但对充电引起的发热基本不起作用），但我自己在使用支持 QC 2.0 的充电器时没感觉到太严重的发热（未安装模块或修改配置），除非在充电时继续长时间使用。

* 问题 5
大概率是在 [20210815](https://github.com/BYZYB/android_device_xiaomi_libra/releases/tag/v2021.08.15) 版本新加入的磁盘配额支持引起的兼容性问题，如果 TWRP 的内核不支持这项功能（或挂载分区时未指定 `quota` 选项），可能会导致挂载失败，而非磁盘加密的原因（我向来反对强制加密，毕竟性能是首要因素）。例如，之前我在 Mix-2 上曾禁用了配额支持并删除了相关的挂载选项，直接导致开机时无法挂载 `/data` 而无限重启；由于磁盘配额会在该分区第一次使用 `quota` 选项时自动应用（具体参数由 Android 指定），因此用户通常感觉不到（除非遇到类似这种情况）。磁盘配额支持实际上是应当启用的（实际上最初就是启用的，只是早期裁剪内核时被顺便关掉了，直到这个月才再次打开），至少在新设备上比较常见，这样做的意义可以参考[官方文档](https://source.android.google.cn/devices/storage/faster-stats)。此外，`/data` 分区的加密状态可以在“设置 > 安全 > 加密与凭据 > 加密手机”中进行确认，若显示“手机未加密”则确实没有加密（新启用磁盘配额的 4c 和始终启用的 Mix-2 均显示未加密）。
**【更新】我自己的 4c 在 TWRP-3.3.1.0 中可以正常挂载 `/data` 分区，查看或修改文件时并未出现问题。** ~~TWRP-3.3.1.0 的内核启用了配额支持，但未启用 Android 8.0+ 使用的 QFMT_V2，可能会引发问题。我直接替换了现有 TWRP 镜像中的内核部分，理论上是可行的，你可以尝试一下（解压后再刷入，若 `/data` 无法访问则可通过 ADB 将 img 文件推送到 `/cache` 分区）：[TWRP-3.3.1.0-libra-rebuilt.zip](https://github.com/BYZYB/android_device_xiaomi_libra/files/7007615/TWRP-3.3.1.0-libra-rebuilt.zip)~~ 原版的 [TWRP-3.3.1.0](https://androidfilehost.com/?fid=8889791610682882451) 默认支持磁盘配额，因此不应存在问题（所以我一直没有意识到，直到有使用旧版 TWRP 的用户提供反馈），建议使用这个版本（如果有空，我也会自行编译新版的 TWRP 测试效果，上面这个版本是很久之前在 AFH 上找到的）。

* 问题 7
如果多任务切换键也不能使用（或者有其他奇怪的问题，具体可以想象一下在开机向导强制退出时的场景），应该是某次意外重启导致的设置数据损坏（常见问题，根本原因是内核的 fsync 功能目前需要关闭，否则会在开机后数秒内导致内核崩溃，这可能直接导致尚未写入磁盘的数据丢失或损坏，尤其是在使用 F2FS 的情况下；我的 Mix-2 在也曾复现过相同的问题，但好在可以正常启用 fsync，启用后几乎没再发生过意外重启）。既可以通过再进行一次首次开机配置（SetupWizrad），也可以直接运行设置向导的 `SetupWizardExitActivity`（命令如下，需要启用 ADB Root）：
```
adb shell
    pm enable org.lineageos.setupwizard/org.lineageos.setupwizard.SetupWizardExitService
    am start-activity org.lineageos.setupwizard/org.lineageos.setupwizard.SetupWizardExitActivity
```
或者通过命令行手动配置相关属性解决这类问题（适用于大部分 Android 设备，也需要 Root 权限，不建议）：
```
adb shell
    settings put secure user_setup_complete 1
    settings put global device_provisioned 1
    sync && reboot
```

**Comment by laoleic4** [comment]
您好，按照你说的方法是解决了大部分问题，但BitGapps的官网不提供下载链接了，所导致的是我无法下载安装并检测WiFi是否可以正常连接等，虽然我人在国内，但Gapps对于我来说很重要，有了Gapps我就能正常接收Play版QQ和Play版微信的消息、游玩Google Play上面需要Play Games验证的游戏（并不是什么大型游戏）使用需要Play服务支持的应用等，所以能不能在下个月的卡刷包出来前尝试修复下安装Gapps后出现的问题吗（我个人用的是OpenGapps和NikGapps进行刷入安装使用，然后本人是把小米4C当做主力机来使用）

**Comment by BYZYB** [comment]
> 您好，按照你说的方法是解决了大部分问题，但BitGapps的官网不提供下载链接了，所导致的是我无法下载安装并检测WiFi是否可以正常连接等，虽然我人在国内，但Gapps对于我来说很重要，有了Gapps我就能正常接收Play版QQ和Play版微信的消息、游玩Google Play上面需要Play Games验证的游戏（并不是什么大型游戏）使用需要Play服务支持的应用等，所以能不能在下个月的卡刷包出来前尝试修复下安装Gapps后出现的问题吗（我个人用的是OpenGapps和NikGapps进行刷入安装使用，然后本人是把小米4C当做主力机来使用）

刚看了 TG 群组，BitGapps 的服务器可能出了问题（虽然看起来像是删库跑路了），我在群里找了一份日期比较新的，今天先自己测试一下是否可用。日常使用这个 ROM 是完全可行的，直到两个月之前 4c 也曾是我的主力机，使用体验尚可（毕竟是老机型，用了 6 年还说得过去）；而不同之处在于我不使用 GAPPs，也不会经常测试主流 GAPPs 的兼容性。况且，除 `/system` 分区空间不足的问题外，大多数与 GAPPs 相关的问题不一定是 ROM 导致的，所以未必能进行“修复”。
下一个 lineage-18.1 版本计划关闭 Transparent Hugepages，因为大内存页并不能在 4c 有限的内存空间中（2~3 GB）起到明显作用，反而会导致内存更快耗尽（最坏情况下会引发内核崩溃），可以先刷入[这个](https://github.com/BYZYB/android_device_xiaomi_libra/releases/download/v2021.08.15/AnyKernel3-aqua+libra-20210828-4f9d1f1.zip)内核试试（最新的内核通常可以在 [Releases](https://github.com/BYZYB/android_device_xiaomi_libra/releases/latest) 页面找到，是与 ROM 分开更新的）。
**【更新】BitGapps（[arm64-11.0.0-R34](https://cowtransfer.com/s/8eb4676756ad4a) | 链接有效期 24 小时）实测不会引起系统功能异常，也不会导致重启。** 建议事先安装最新的 [Google WebView](https://play.google.com/store/apps/details?id=com.google.android.webview)，然后删除 ROM 自带的 WebView，以预留足够的存储空间。如果之前安装过其它 GAPPs（无论是否失败），建议先格式化 `/system`，重新刷入 ROM 后再安装。

**Comment by mr-south-guo** [comment]
提供另外一个Gapps的解决方案：[MagiskGApps](https://sourceforge.net/projects/magiskgapps/)。我在20210718版的ROM上用的，完全不占用system分区且可以随时开关，感觉很不错。不能100%肯定在20210815版的ROM也正常（理论上应该可以），因为刚刷了20210815之后，不知为什么就启动不了系统了，只能进入TWRP。

**Comment by BYZYB** [comment]
> 提供另外一个Gapps的解决方案：[MagiskGApps](https://sourceforge.net/projects/magiskgapps/)。我在20210718版的ROM上用的，完全不占用system分区且可以随时开关，感觉很不错。不能100%肯定在20210815版的ROM也正常（理论上应该可以），因为刚刷了20210815之后，不知为什么就启动不了系统了，只能进入TWRP。

这类以 Magisk 模块形式安装的 GAPPs 确实是相对安全的，因为实际存储在 `/data` 也不存在空间不足的问题。既然上一个版本是正常的，最新的 0815 也应该可行；可能是你刷入新版本时没有格式化 `/system`（如果此前有刷入 GAPPs，则建议这样做），可能是这个版本的 GAPPs 与大内存页不兼容（如果你没刷入新的内核），也可能是单纯的文件损坏（尤其易在硬重启之后发生）；好在目前确有方案能正常使用 GAPPs 并满足个人需求。
