### ISSUE TITLE
System image space is not enough to flash pico Gapps

### ISSUE THREAD

**Issue by dibyanugraha** [BYZYB/android_device_xiaomi_libra#23]
Tested in build lineage-18.1-20211113. Mi 4c 3/32.

I apologize for opening this issue, but seems even after removing NotoCJK.ttf, bold, italic, there still is not enough space to flash Pico Gapps (Flame/Open).

Removing webview is the last effort to make space for pico gapps, but it breaks the first time Google initialization apps (got black screen on screen that should show enter Google account or skip it).

Is there anything else that could be removed to make room for pico gapps to be flashed?

**Comment by BYZYB** [comment]
> Tested in build lineage-18.1-20211113. Mi 4c 3/32.
> 
> I apologize for opening this issue, but seems even after removing NotoCJK.ttf, bold, italic, there still is not enough space to flash Pico Gapps (Flame/Open).
> 
> Removing webview is the last effort to make space for pico gapps, but it breaks the first time Google initialization apps (got black screen on screen that should show enter Google account or skip it).
> 
> Is there anything else that could be removed to make room for pico gapps to be flashed?

I'm kind of surprised that the GAPPs package has become huge these days. As I remember, removing the NotoCJK fonts should be enough for OpenGAPPs "pico" version some times ago (at least on Android 10).

I don't think removing other prebuilt apps is a good idea, as none of them could be replaced by Google ones from a "pico" package (also saves less space than Webview). A better choice is to install Google Webview into "/data", just like installing other apps (before the GAPPs package).

**Comment by dibyanugraha** [comment]
> A better choice is to install Google Webview into "/data", just like installing other apps (before the GAPPs package).

Do you mean move the webview.apk right after flashing the rom into /data? Does that guarantee webview will still work?

**Comment by BYZYB** [comment]
> > A better choice is to install Google Webview into "/data", just like installing other apps (before the GAPPs package).
> 
> Do you mean move the webview.apk right after flashing the rom into /data? Does that guarantee webview will still work?

No, I mean to install Google Webview after boot, then reboot to recovery and install GAPPs. You could download the APK from some websites like APKMirror and [APKPure](https://apkpure.com/android-system-webview/com.google.android.webview).
