### ISSUE TITLE
Unroot help

### ISSUE THREAD

**Issue by gordio** [BYZYB/android_device_xiaomi_libra#27]
How I can unroot system image, and after (optional) use magisk to hide root state from some apps?

**Comment by BYZYB** [comment]
> How I can unroot system image

The system is actually not rooted on lineage-17.1/18.1, only adb root is available. No app could request root access or execute `su`.

> and after (optional) use magisk to hide root state from some apps

New version of Magisk has removed MagiskHide in official builds. [Shamiko](https://github.com/LSPosed/LSPosed.github.io/releases) is another root hide solution, working as a Magisk (Zygisk) module.

**Comment by gordio** [comment]
> The system is actually not rooted on lineage-17.1/18.1, only adb root is available. No app could request root access or execute `su`.

It's strange. PingID thinks that it's rooted >_<.


> New version of Magisk has removed MagiskHide in official builds. [Shamiko](https://github.com/LSPosed/LSPosed.github.io/releases) is another root hide solution, working as a Magisk (Zygisk) module.

Thank you. I will give it a try. And about Magisk (latest release from GitHub) have that feature in options menu. But I'm still able to add PingID (read as don't work for me) %)
