### ISSUE TITLE
error：NotoSerifCJK-Bold.ttc

### ISSUE THREAD

**Issue by wuwansan** [BYZYB/android_device_xiaomi_libra#28]
error: external/noto-fonts/cjk/Android.bp:20:1: module "NotoSerifCJK-Bold.ttc" variant "android_arm64_armv8-a_cortex-a53": module source path "external/noto-fonts/cjk/NotoSerifCJK-Bold.ttc" does not exist

**Comment by BYZYB** [comment]
> external/noto-fonts/cjk/NotoSerifCJK-Bold.ttc" does not exist

Did you apply the [patch](https://github.com/BYZYB/android_device_xiaomi_libra/blob/lineage-18.1/repo_18.diff#L362) about noto-fonts? It's not necessary to apply this one unless you need full weight Chinese/Japanese/Korean fonts.

To resolve this issue, run `git reset --hard` in `external/noto-fonts` (if you don't need the CJK fonts), or download the font files and copy them to right places.

- [NotoSansCJK.ttc](https://github.com/googlefonts/noto-cjk/blob/main/Sans/SuperOTC/NotoSansCJK.ttc.zip)
- [NotoSerifCJK-Bold.ttc](https://github.com/googlefonts/noto-cjk/blob/main/Serif/OTC/NotoSerifCJK-Bold.ttc)
