### ISSUE TITLE
Sim preference reset after reboot in dualsim [lineage-16.0 | lineage-17.1]

### ISSUE THREAD

**Issue by tempte** [BYZYB/android_device_xiaomi_libra#6]
In dualsim configuration  preferences for sim card usage reset to default after each reboot (Calls preference, SMS preference, mobile data).

**Comment by BYZYB** [comment]
> In dualsim configuration preferences for sim card usage reset to default after each reboot (Calls preference, SMS preference, mobile data).

This is a known issue that existed since Android 9. As I only have one SIM card, could you send me the logcat with dual SIM after boot completed? I'm not sure this could be fixed, just like the mobile signal (the device needs about one minute to show the real value of signal just after boot, which shows "no signal" before).

**Comment by tempte** [comment]
It seems the system remembers right SIM at least for data, but Mobile data is off each time after reboot. Once you turn Mobile data on (swipe from the top of the screen and turn it on) right SIM is selected and no other interaction needed.. until next reboot.

**Comment by tempte** [comment]
The below solution worked:
1. extract sim tray, place SIM card to be used for data to slot 2 (the one closer to the edge of the phone), the other one to slot 1;
2. after SIMs initialize - select any calls/sms SIM preferences in settings but data set for sim in slot 2;
3. reboot, next boot all settings will be in place.

PS
- one sim card is local (for data/calls) and one is in roaming (for calls).
- insert the tray with data SIM in slot 1, roaming SIM in slot 2 and set preferences for calls/SMS only (without data preference) and it will allow to keep settings after reboot for both cards; but in case data preference is set for slot 1 (with data SIM) all settings for this slot (incl calls/sms) will reset after reboot, while for slot 2 will be kept as configured.
- both SIMs work as expected in any of 2 slots, but preferences are not reset after reboot only with data SIM placed in slot 2.
