### ISSUE TITLE
Mi4-LTE support

### ISSUE THREAD

**Issue by super-keys** [BYZYB/android_device_xiaomi_libra#8]
Hello, does this rom support Xiaomi 4 LTE?
I have swiped other aosp7.1.1. I can’t access the Internet with a mobile data card. I can access the Internet with a normal data card. I don’t know if this rom supports Xiaomi 4lte.
Thank you

**Comment by BYZYB** [comment]
It's normal that someone may mismatch **Mi-4c** with **Mi-4C**. The former one is "libra" with Snapdragon 808, but the latter one is a model of Mi-4 "cancro" with Snapdragon 801. So this rom certainly **not support** Mi-4C (Mi-4 LTE), you may find the rom you like on XDA or some other websites.

**Comment by super-keys** [comment]
Thank you
